# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: starbucks
  template:
    metadata:
      labels:
        app: starbucks
    spec:
      containers:
      - name: starbucks
        image: xyushman/starbucks:latest
        ports:
        - containerPort: 3000
